Repository XRTK/com.xrtk.core, pull requests merged in 2019-06, with the labels that each got.

#183 Getting started docs
  articles/00-DownloadingTheXRTK.md
  articles/01-GettingStarted.md
  articles/A01-XRTKUPMInstall.md
  articles/Images/00_XRTKUPMInstall_01_UnityPackages.png
  articles/Images/00_XRTKUPMInstall_02_PackageManagerMenu.png
  articles/Images/00_XRTKUPMInstall_03_PackageManager.png
  articles/Images/00_XRTKUPMInstall_04_XRTKAutoInstallAsset.png
  articles/Images/00_XRTKUPMInstall_05_XRTKDialog.png
  articles/Images/00_XRTKUPMInstall_06_LocatePackagesFolder.png
  articles/Images/00_XRTKUPMInstall_07_ManifestJSON.png
  articles/Images/00_XRTKUPMInstall_08_ManifestDependandcies.png
  articles/Images/00_XRTKUPMInstall_08_PackageReimport.png
  articles/Images/00_XRTKUPMInstall_10_XRTKVersioning.png
  articles/Images/01_01_MixedRealityConfigure.png
  articles/Images/01_02_MixedRealityScene.png
  articles/Images/01_03_MixedRealityActiveProfile.png
  articles/Images/01_04_MixedRealityProfileView.png
  articles/Images/01_05_MixedRealityProfileClone.png
  articles/Images/01_06_MixedRealityProfileCloneButton.png
  articles/toc.yml
Labels: Ready For Review

#202 Android oculus support
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/OpenVR/OculusGoControllerMappingProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/OpenVR/OculusGoControllerMappingProfile.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/SupportedControllerType.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Data/EditorWindowOptions.json
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/DataProviders/Controllers/OpenVR/OculusGoControllerMappingProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/DataProviders/Controllers/OpenVR/OculusGoControllerMappingProfileInspector.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusGoController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusGoController.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OpenVRDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/GenericJoystickController.cs
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/OculusGoController_black.png
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/OculusGoController_black.png.meta
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/OculusGoController_black_scaled.png
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/OculusGoController_black_scaled.png.meta
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/OculusGoController_white.png
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/OculusGoController_white.png.meta
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/OculusGoController_white_scaled.png
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/OculusGoController_white_scaled.png.meta
Labels: Ready For Review

#182 Xrt kvs mrtk
  articles/A02-ChoosingXRTKvsMRTK.md
  articles/toc.yml
Labels: Ready For Review

#211 Cancellation for indefinite awaiters when changing play mode state
  XRTK-Core/Packages/com.xrtk.core/Utilities/Async/Awaiters.cs
Labels: Enhancement, Ready For Review

#219 Update XRTK logo
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/MixedRealityInspectorUtility.cs
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/XRTK_Logo.png
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/XRTK_Logo.png.meta
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/XRTK_Logo_Black.png
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/XRTK_Logo_White.png
  XRTK-Core/Packages/com.xrtk.core/StandardAssets/Textures/XRTK_Logo_White.png.meta
Labels: Enhancement

#220 Dev meta fixes
  XRTK-Core/Packages/com.xrtk.core/README.md.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildDeployPreferences.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildDeployWindow.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildInfo.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildInfoExtensions.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/IBuildInfo.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/MixedRealityAppIcon.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpBuildDeployPreferences.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpBuildInfo.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpPlayerBuildTools.cs.meta
Labels: Ready For Review

#213 Native Oculus Pre-Updates
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/OpenVR/OculusGoControllerMappingProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/OpenVR/OculusRemoteControllerMappingProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/OpenVR/OculusTouchControllerMappingProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/OpenVR/ViveWandControllerMappingProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/IMixedRealityService.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusGoOpenVRController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusGoOpenVRController.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusRemoteOpenVRController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusRemoteOpenVRController.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OpenVRDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/ViveKnucklesOpenVRController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/ViveKnucklesOpenVRController.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/ViveWandOpenVRController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/ViveWandOpenVRController.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Services/BaseService.cs
  XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
Labels: Breaking Change

#224 updated editor to 2019.1.8f1
  XRTK-Core/ProjectSettings/ProjectSettings.asset
  XRTK-Core/ProjectSettings/ProjectVersion.txt
Labels: Ready For Review

#225 Ported some build window perf fixes
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildDeployWindow.cs
Labels: Ready For Review
