Repository XRTK/com.xrtk.core, pull requests merged in 2019-05, with the labels that each got.

#142 cleaned up Vector2 interaction mapping with faster code
  XRTK-Core/Assets/XRTK.Tests/InputSystem/TestFixture_02_InteractionDefinitionTests.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/MixedRealityInteractionMapping.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/BoundsExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/GameObjectExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Services/BoundarySystem/MixedRealityBoundarySystem.cs
  XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/MixedRealityInputSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Services/TeleportSystem/MixedRealityTeleportSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/InputMappingAxisUtility.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Physics/Interpolator.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Physics/TwoHandMoveLogic.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Rendering/ClippingPlane.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Rendering/ClippingSphere.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/ConstantViewSize.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/InBetween.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/Solver.cs
Labels: Enhancement

#150 even better if no cache required
  XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/MixedRealityInteractionMapping.cs
Labels: Enhancement

#151 Fixed some issues with the controller popup window
  XRTK-Core/Packages/com.xrtk.core/Inspectors/ControllerPopupWindow.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Data/EditorWindowOptions.json
Labels: Bug

#172 Fixed the path for finding msbuild for 2019+
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
Labels: Bug

#178 Added SetRedneringActive game object extension
  XRTK-Core/Packages/com.xrtk.core/Extensions/GameObjectExtensions.cs
Labels: Enhancement

#175 EditorBuildSettings.scenes fixes
  XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityPreferences.cs
Labels: Bug

#181 Updated Awaiter.WaitUntil extension method with indefinite option
  XRTK-Core/Packages/com.xrtk.core/Services/BaseEventSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Async/Awaiters.cs
Labels: Enhancement

#198 Warnings as errors cleanup
  XRTK-Core/Packages/com.xrtk.core/Extensions/CanvasExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/GameObjectExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/PrefabPropertyDrawer.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/FastSimplexNoise.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Gltf/Serialization/Importers/GltfEditorImporter.cs
Labels: Ready For Review

#205 ported an update to solvers to use the current lifetime
  XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/SolverHandler.cs
Labels: Ready For Review
