Repository XRTK/com.xrtk.core, pull requests merged in 2019-10, with the labels that each got.

#368 Updated Spatial Awareness Parent Object Transform to fix teleporting
  XRTK-Core/Packages/com.xrtk.core/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
Labels: Blocked, Bug, Ready for review

#371 Make sure we ping the cloned profile
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
Labels: Bug, Ready for review

#374 Ensure we always start a service if only the editor flag is set
  XRTK-Core/Packages/com.xrtk.core/Utilities/PlatformUtility.cs
Labels: Bug, Ready for review

#372 moved symbolic link settings into XRTK.Generated
  XRTK-Core/Assets/XRTK.Generated.meta
  XRTK-Core/Assets/XRTK.Generated/SymbolicLinkSettings.asset
  XRTK-Core/Assets/XRTK.Generated/SymbolicLinkSettings.asset.meta
Labels: Ready for review

#375 Update UPM version to 0.1.22
  XRTK-Core/Packages/com.xrtk.core/package.json
Labels: Ready for review

#380 Dev/poco input events
  XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/IMixedRealityInputSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/MixedRealityInputSystem.cs
Labels: Breaking Change, Enhancement, In Progress

#381 Some quick review and change requests for feature/hand-simulation
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/BaseMixedRealityControllerMappingProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/Hands/HandControllerDataProviderProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/Hands/UnityEditorHandControllerDataProviderProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerMappingProfiles.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerVisualizationProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/BaseHandControllerDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/UnityEditor/UnityEditorHandControllerDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/UnityEditor/UnityEditorHandPose.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/UnityEditor/UnityEditorHandPoseData.cs
Labels: Ready for review

#384 Added body tracking to solver handler
  XRTK-Core/Packages/com.xrtk.core/Definitions/Utilities/TrackedObjectType.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Solvers/SolverHandler.cs
Labels: Breaking Change, Enhancement, Ready for review

#387 Fix prefab attribute
  XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/PrefabPropertyDrawer.cs
Labels: Bug, Ready for review

#388 Update FUNDING.yml
  .github/FUNDING.yml
Labels: Ready for review

#393 Updated Handedness use in the Visualization inspector
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
Labels: Enhancement

#396 Also checks if an xr device is present for stereoscopic check
  XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs
Labels: Bug
