Repository XRTK/com.xrtk.core, pull requests merged in 2019-07, with the labels that each got.

#234 Visualisation fix for #233
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerVisualizationProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Data/EditorWindowOptions.json
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityControllerVisualizationProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OpenVRDataProvider.cs
Labels: Open VR

#237 Missing updates required in Core for Oculus module
  XRTK-Core/Packages/com.xrtk.core/AssemblyInfo.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/MixedRealityInteractionMapping.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/InteractionMappingsExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/InteractionMappingsExtensions.cs.meta
  XRTK-Core/Packages/com.xrtk.core/package.json
Labels: Oculus

#239 updated symbolic link verification
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs
Labels: Bug

#241 updated editor to 2019.1.10f1
  XRTK-Core/Assets/SymbolicLinkSettings.asset
  XRTK-Core/ProjectSettings/ProjectVersion.txt
Labels: Enhancement

#243 Added SetMeshVisibility convenience method to SpatialAwarenessSystem
  XRTK-Core/Packages/com.xrtk.core/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
Labels: Enhancement, Ready For Review

#244 Added transform extension to set all colliders active
  XRTK-Core/Packages/com.xrtk.core/Extensions/TransformExtensions.cs
Labels: Enhancement, Ready For Review

#245 Misc cleanup and RayStep direction bug fix
  XRTK-Core/Packages/com.xrtk.core/Definitions/InputSystem/MixedRealityInputAction.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Physics/RayStep.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Physics/MixedRealityRaycaster.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/PlatformUtility.cs
Labels: Bug, Ready For Review

#246 Fixed package settings serialization bug
  XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityPackageSettings.cs
Labels: Bug, Ready For Review

#249 bumped version to 0.1.14
  XRTK-Core/Packages/com.xrtk.core/package.json
Labels: Ready For Review

#257 Ensure we set the scene in the build settings if no scenes are available
  XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityPreferences.cs
Labels: Bug, Ready For Review
