Repository XRTK/com.xrtk.core, pull requests merged in 2019-09, with the labels that each got.

#307 Fix to resolve Git Tag sorting issue #300
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackageUtilities.cs
Labels: Bug, Ready for review

#305 Fixed a warning during first start
  XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityPackageSettings.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/MixedRealityEditorSettings.cs
Labels: Bug, Enhancement, Ready for review

#308 Oculus Controller mapping update
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/GenericJoystickController.cs
Labels: Bug, In Progress

#310 Release 0.1.18
  .github/FUNDING.yml
  CODING_GUIDELINES.md
  XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityPackageSettings.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/StringExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/TransformExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackageUtilities.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/UnityInput/GenericJoystickController.cs
  XRTK-Core/Packages/com.xrtk.core/Services/DiagnosticsSystem/MixedRealityToolkitVisualProfiler.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/MixedRealityEditorSettings.cs
  XRTK-Core/Packages/com.xrtk.core/package.json
  XRTK-Core/Packages/manifest.json
  XRTK-Core/ProjectSettings/ProjectVersion.txt
Labels: Blocked

#304 Added Environment OS Platform version switch case
  XRTK-Core/Packages/com.xrtk.core/Extensions/ProcessExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/GitUtilities.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UwpAppxBuildTools.cs
Labels: Bug, Ready for review

#315 fixed missing access modifier
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackagesWindow.cs
Labels: Bug

#317 Proper UPM registry support
  XRTK-Core/Assets/SymbolicLinkSettings.asset
  XRTK-Core/Assets/XRTK.Seed/MixedRealityPackageSeed.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityPackageInfo.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityPackageInfo.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityPackageSettings.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityPackageSettings.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityPreferences.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages.meta
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackageSettingsInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackageSettingsInspector.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackageUtilities.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackageUtilities.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackagesWindow.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/Packages/MixedRealityPackagesWindow.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/SymbolicLinks/SymbolicLinkerWindow.cs
  XRTK-Core/Packages/com.xrtk.core/XRTK.asmdef
  XRTK-Core/Packages/com.xrtk.core/package.json
  XRTK-Core/Packages/manifest.json
Labels: Breaking Change, Ready for review

#319 Updated mappings due to issues following #312
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/GenericOpenVRController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs
Labels: Open VR, Ready for review

#256 Updated Build Tools
  XRTK-Core/Packages/com.xrtk.core/Extensions/ProcessExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/BuildDeployWindow.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/LuminPlayerBuildTools.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/LuminPlayerBuildTools.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs
Labels: Enhancement, Ready for review

#327 Fixed canvas utility removing itself
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/CanvasEditorExtension.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/CanvasUtility.cs
Labels: Bug, Ready for review

#333 pull the sdk and core by default
  XRTK-Core/Assets/XRTK.Seed/MixedRealityPackageSeed.cs
Labels: Ready for review

#338 Update README.md
  README.md
Labels: Ready for review

#339 removed unsused declarations and a bit of formatting
  XRTK-Core/Packages/com.xrtk.core/Extensions/BoundsExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/LayerExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/TextureExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/UnityObjectExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityStandardShaderGUI.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealitySpeechCommandsProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/GitUtilities.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/IMixedRealityFocusProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/MixedRealityControllerMapping.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/OpenVR/OpenVRDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/MixedRealityAppIcon.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Gltf/Serialization/ConstructGltf.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Gltf/Serialization/GltfUtility.cs
Labels: Ready for review

#337 Added a delay call to all object pings and reworked configure method
  XRTK-Core/Packages/com.xrtk.core/Extensions/EditorClassExtensions/ScriptableObjectExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityToolkitInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
Labels: Bug, Ready for review

#341 Make sure we're not set to none
  XRTK-Core/Packages/com.xrtk.core/Utilities/PlatformUtility.cs
Labels: Bug

#348 removed unused ugui reference
  XRTK-Core/Packages/com.xrtk.core/Inspectors/XRTK.Inspectors.asmdef
Labels: Ready for review

#350 Updated collider extension
  XRTK-Core/Packages/com.xrtk.core/Extensions/ColliderExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/ColliderExtensions.cs.meta
Labels: Ready for review

#355 Fixed editor platform support checking
  XRTK-Core/Packages/com.xrtk.core/Utilities/PlatformUtility.cs
Labels: Bug, Ready for review

#356 Improved package path lookup
  XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/MixedRealityEditorSettings.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/PathFinder.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/Editor/PathFinder.cs.meta
Labels: Enhancement, Ready for review

#357 Added a way to define your own generated path for profiles
  XRTK-Core/Assets/XRTK.Tests/TestUtilities.cs
  XRTK-Core/Assets/XRTK.Tests/XRTK.Tests.asmdef
  XRTK-Core/Packages/com.xrtk.core/Extensions/EditorClassExtensions.meta
  XRTK-Core/Packages/com.xrtk.core/Extensions/EditorClassExtensions/XRTK.Extensions.EditorClassExtensions.asmdef
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions.meta
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/ScriptableObjectExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/ScriptableObjectExtensions.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityPreferences.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityToolkitInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityToolkitConfigurationProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/SymbolicLinks/SymbolicLinker.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/XRTK.Inspectors.asmdef
Labels: Breaking Change, Enhancement, Ready for review

#359 updated assembly references to use guids
  XRTK-Core/Packages/com.xrtk.core/Inspectors/XRTK.Inspectors.asmdef
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/BuildAndDeploy/XRTK.Utilities.Build.asmdef
  XRTK-Core/Packages/com.xrtk.core/Utilities/Gltf/Serialization/Importers/XRTK.Utilities.Gltf.Importers.asmdef
  XRTK-Core/Packages/com.xrtk.core/XRTK.asmdef
Labels: Ready for review

#361 Update to improve focus initialization and pre-updates for the InputAction Refactor
  XRTK-Core/Packages/com.xrtk.core/Extensions/InteractionMappingsExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Services/InputSystem/FocusProvider.cs
Labels: Enhancement

#362 Added unity's il2cpp attribute
  XRTK-Core/Packages/com.xrtk.core/Attributes/Il2CppSetOptionAttribute.cs
  XRTK-Core/Packages/com.xrtk.core/Attributes/Il2CppSetOptionAttribute.cs.meta
Labels: Enhancement, Ready for review

#367 Should be able to use digital axis type when setting float data
  XRTK-Core/Packages/com.xrtk.core/Definitions/Devices/MixedRealityInteractionMapping.cs
Labels: Bug, Ready for review
