Repository XRTK/com.xrtk.core, pull requests merged in 2020-11, with the labels that each got.

#676 Fixing gltf serialization
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfAccessor.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfAccessorSparseIndices.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfAnimationChannelTarget.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfAnimationSampler.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfBufferView.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfCamera.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfMeshPrimitive.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Schema/GltfSampler.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Gltf/Serialization/GltfConversions.cs
Labels: Ready for review

#680 fix/tracked pose access
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Simulation/Hands/SimulatedHandControllerDataProvider.cs
Labels: Ready for review

#684 Add first tesplan for SDK import and configure
  articles/appendices/A01-CodingGuidelines.md
  articles/appendices/A02-ChoosingXRTKvsMRTK.md
  articles/testplans/TP-00_Import-XRTK.SDK-And_Configure.md
  articles/testplans/TP-01_Import-XRTK.Oculus-Without-XRTK.SDK.md
  articles/testplans/TP_Overview.md
  articles/toc.yml
Labels: Ready for review

#678 Self hosted pipelines
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Speech/WindowsDictationDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Speech/WindowsSpeechDataProvider.cs
  XRTK-Core/ProjectSettings/ProjectSettings.asset
  azure-pipelines.yml
  azure_pipelines/common.yml
  azure_pipelines/stages/publish.yml
  azure_pipelines/stages/steps/build-docs.yml
  azure_pipelines/stages/steps/build-unity-player.yml
  azure_pipelines/stages/steps/export-package-seed.yml
  azure_pipelines/stages/steps/install-unity.yml
  azure_pipelines/stages/steps/return-unity-license.yml
  azure_pipelines/stages/steps/run-unity-tests.yml
  azure_pipelines/stages/steps/upm-package-info.yml
  azure_pipelines/stages/unity-build.yml
Labels: Enhancement, Ready for review

#687 Updated symbolic link Utilities
  XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityPreferences.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLink.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/SymbolicLinks/SymbolicLinker.cs
Labels: Bug, Enhancement, Ready for review

#692 Fixed simulated hand data provider Tracked Hand Pose list rendering
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/Controllers/Hands/BaseMixedRealityHandControllerDataProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/Controllers/Simulation/SimulatedHandControllerDataProviderProfileInspector.cs
Labels: Bug, Ready for review

#690 Added json files to the list of UnityFileExtensions
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/UnityFileHelper.cs
Labels: Bug, Ready for review

#695 Fix NRE on package asset import
  XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
Labels: Bug, Ready for review

#696 Fix condition for package installer
  XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
Labels: Ready for review

#704 updated playmode/editor mode change transitions
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
  XRTK-Core/Packages/com.xrtk.core/Tests/Core/TestFixture_01_MixedRealityToolkitTests.cs
  XRTK-Core/Packages/com.xrtk.core/Tests/InputSystem/TestFixture_03_InputSystemTests.cs
  XRTK-Core/Packages/manifest.json
  XRTK-Core/Packages/packages-lock.json
Labels: Bug, Ready for review
