Repository XRTK/com.xrtk.core, pull requests merged in 2020-02, with the labels that each got.

#452 Controller Mapping / Provider validations part 2
  XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_02_MixedRealityToolkitUtilityTests.cs
  XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_02_MixedRealityToolkitUtilityTests.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerDataProvidersProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerMappingProfiles.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/ValidateConfiguration.cs
Labels: In Progress

#456 Change Requests from Validation Changes
  XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_02_MixedRealityToolkitUtilityTests.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/ValidateConfiguration.cs
Labels: Bug, Ready for review

#459 Add a utility to draw a capsure wire gizmo
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/MixedRealityInspectorUtility.cs
Labels: Enhancement, Ready for review

#460 Fix controller data providers inspector name
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/MixedRealityControllerDataProvidersProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/MixedRealityControllerDataProvidersProfileInspector.cs.meta
Labels: Ready for review
