Repository XRTK/com.xrtk.core, pull requests merged in 2020-12, with the labels that each got.

#708 Fix missing virtual keyword for OnApplicationPause in BaseService
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/BaseService.cs
Labels: Ready for review

#711 Docs update
  CONTRIBUTING.md
  articles/01-DownloadingTheXRTK.md
  articles/toc.yml
  docfx_project/docfx.json
  docfx_project/templates/darkfx/partials/head.tmpl.partial
  docfx_project/templates/darkfx/styles/main.css
  docfx_project/templates/material/styles/main.css
  docs/logo.png
  images/DownloadingTheXRTK/ScopedRegistry.png
Labels: Ready for review

#712 added error message when we cannot enter play mode
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
Labels: Bug, Ready for review

#714 Docs/2019.5 update
  articles/00-GettingStarted.md
  articles/01-DownloadingTheXRTK.md
  images/DownloadingTheXRTK/UnityPackageManager-Advanced.jpg
  images/DownloadingTheXRTK/UnityPackageManager-MyRegistries.jpg
  images/DownloadingTheXRTK/UnityPackageManager-ScopedRegistries.jpg
  images/DownloadingTheXRTK/UnityPackageManager-XRTKRegistries.jpg
Labels: Ready for review

#715 Update input actions inspector to use reordable list
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/MixedRealityInputActionsProfileInspector.cs
Labels: Ready for review

#713 Implement Grip Pose Input action for Oculus Touch controllers
  XRTK-Core/Packages/com.xrtk.core/Editor/Data/EditorWindowOptions.json
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/BaseController.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/OpenVR/GenericOpenVRController.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs
Labels: In Progress

#718 Implement grip pose input action for Oculus Touch controller's
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/OpenVR/OculusTouchOpenVRController.cs
Labels: Ready for review

#719 Misc fixes for GUID regeneration issues
  XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs
  articles/00-GettingStarted.md
  articles/04-KnownIssues.md
  articles/toc.yml
Labels: Ready for review

#723 updated project to 2019.4.16
  XRTK-Core/Packages/packages-lock.json
  XRTK-Core/ProjectSettings/ProjectVersion.txt
Labels: Ready for review

#726 Teleport Mode for Teleport System
  .gitignore
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityTeleportSystemProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/TeleportSystem/MixedRealityTeleportSystemProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/TeleportSystem/MixedRealityTeleportSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/TeleportSystem/TeleportMode.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/TeleportSystem/TeleportMode.cs.meta
Labels: Ready for review

#729 Feature/721 teleport input action
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/TeleportSystem/MixedRealityTeleportSystemProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/TeleportSystem/MixedRealityTeleportValidationDataProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/TeleportSystem/MixedRealityTeleportSystemProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/TeleportSystem/MixedRealityTeleportValidationDataProviderProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/TeleportSystem/IMixedRealityTeleportSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/TeleportSystem/MixedRealityTeleportSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/TeleportSystem/MixedRealityTeleportValidationDataProvider.cs
Labels: Ready for review

#732 Attempt to fix wireframe shader
  XRTK-Core/Packages/com.xrtk.core/Runtime/StandardAssets/Shaders/XRTK_Wireframe.shader
Labels: Ready for review

#734 Fix camera / head position appears way above ground for OpenVR
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/CameraSystem/BaseCameraDataProvider.cs
Labels: Ready for review

#735 Fix to resolve issue where an error is generated if the MixedRealityToolkit is selected when a configuration is applied.
  XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
Labels: Ready for review

#733 Updating test plans for 2019.4
  articles/testplans/TP-00_Import-XRTK.SDK-And_Configure.md
  articles/testplans/TP-01_Import-XRTK.Oculus-Without-XRTK.SDK.md
  articles/testplans/TP-01_Import-XRTK.Oculus.md
  articles/testplans/TP-02_Import-XRTK.UWP.md
  articles/testplans/TP_Overview.md
Labels: Ready for review

#736 Added information that when "None" is set as the teleport system provider, than an INSTANT teleport is performed
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/TeleportSystem/MixedRealityTeleportSystemProfileInspector.cs
  XRTK-Core/Packages/packages-lock.json
Labels: Ready for review

#741 Fixed issue where configuration would lose the runtime platform types when installed
  XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/MixedRealityServiceConfiguration.cs
Labels: Bug, Ready for review

#743 Update 04-KnownIssues.md
  articles/04-KnownIssues.md
Labels: Ready for review

#744 added jetbrains rider .idea folder to gitignore
  .gitignore
Labels: Ready for review

#751 fixed missing member in documentation
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/SpatialObservers/BaseMixedRealitySpatialMeshObserverProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/Providers/SpatialObservers/IMixedRealitySpatialMeshObserver.cs
  azure-pipelines.yml
Labels: Breaking Change, Ready for review
