Repository XRTK/com.xrtk.core, pull requests merged in 2020-04, with the labels that each got.

#484 Removed Diagnostics Data Provider Profile
  XRTK-Core/Packages/com.xrtk.core/Definitions/DiagnosticsSystem/MixedRealityDiagnosticsDataProviderProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/DiagnosticsSystem/MixedRealityDiagnosticsDataProviderProfile.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Services/DiagnosticsSystem/BaseMixedRealityDiagnosticsDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Services/DiagnosticsSystem/MixedRealityConsoleDiagnosticsDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Services/DiagnosticsSystem/MixedRealityFrameDiagnosticsDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Services/DiagnosticsSystem/MixedRealityMemoryDiagnosticsDataProvider.cs
Labels: Breaking Change, Ready for review

#485 Added OpenUpm Badges to readme
  README.md
Labels: Ready for review

#486 Updated the controller mapping profile inspector
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/CustomMixedRealityControllerMappingProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/MixedRealityControllerMappingProfilesInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs
Labels: Ready for review

#495 ported game object extension from #216
  XRTK-Core/Packages/com.xrtk.core/Extensions/GameObjectExtensions.cs
Labels: Enhancement, Ready for review

#496 cleaned up base hand controller
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/IMixedRealityHandController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/BaseHandController.cs
Labels: Ready for review

#498 Fix wrong UWP preprocessor directive
  XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/UniversalWindowsPlatform.cs
Labels: Ready for review

#500 Fix/platforms editor exclude
  XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/AndroidPlatform.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/IOSPlatform.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/WebGlPlatform.cs
Labels: Bug

#503 Make use of DefaultHeadHeight setting in editor
  XRTK-Core/Packages/com.xrtk.core/Services/CameraSystem/MixedRealityCameraSystem.cs
Labels: Ready for review

#512 updated input action constructors
  XRTK-Core/Packages/com.xrtk.core/Definitions/InputSystem/MixedRealityInputAction.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/MixedRealityInputActionDropdown.cs
Labels: Ready for review

#511 Added ScriptableObject.GetOrCreateAsset() extensions
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/ScriptableObjectExtensions.cs
Labels: Enhancement, Ready for review

#514 moved some controller interfaces into the correct places
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/MixedRealityControllerVisualizationProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/MixedRealityControllerVisualizationProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/Controllers.meta
  XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/Handlers/IMixedRealityControllerPoseSynchronizer.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/Handlers/IMixedRealityControllerPoseSynchronizer.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/Handlers/IMixedRealityControllerVisualizer.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/InputSystem/Handlers/IMixedRealityControllerVisualizer.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/Hands.meta
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/Hands/IMixedRealityHandController.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/Hands/IMixedRealityHandController.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/Hands/IMixedRealityHandControllerDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/Hands/IMixedRealityHandControllerDataProvider.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/Hands/ISimulatedHandControllerDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/Hands/ISimulatedHandControllerDataProvider.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/IMixedRealityController.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/ISimulatedControllerDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/Providers/Controllers/ISimulatedControllerDataProvider.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/BaseController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/BaseHandController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Hands/BaseHandControllerDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/MixedRealityControllerVisualizationSetting.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Simulation/BaseSimulatedControllerDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Simulation/Hands/SimulatedHandController.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Simulation/Hands/SimulatedHandControllerDataProvider.cs
Labels: Breaking Change, Ready for review

#513 Removed old serialized attributes for older data providers
  XRTK-Core/Packages/com.xrtk.core/Definitions/MixedRealityServiceConfiguration.cs
Labels: Breaking Change, Ready for review

#510 Updated all the inspectors to use a uniform RenderHeader method
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Data/Controllers/Simulation/Hands/SimulatedHandControllerPoseDataInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/MixedRealityToolkitInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/DiagnosticsSystem/MixedRealityDiagnosticsSystemProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/Controllers/Simulation/SimulatedControllerDataProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/Controllers/Simulation/SimulatedHandControllerDataProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/MixedRealityGesturesProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/MixedRealityInputActionsProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/MixedRealityInputDataProvidersProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/MixedRealitySpeechCommandsProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityBoundaryVisualizationProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityNetworkSystemProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityRegisteredServiceProvidersProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityServiceProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwarenessSystem/BaseMixedRealitySpatialObserverProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystemProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/MixedRealityProfilePropertyDrawer.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Utilities/MixedRealityInspectorUtility.cs
Labels: Ready for review

#520 updated boundary system to utilize enable and disable properly
  XRTK-Core/Packages/com.xrtk.core/Services/BoundarySystem/MixedRealityBoundarySystem.cs
Labels: Enhancement, Ready for review

#519 Updated ScriptableObject.CreateAsset method to handle full path names
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/ScriptableObjectExtensions.cs
Labels: Enhancement, Ready for review

#522 fixed an unparented boundary game object
  XRTK-Core/Packages/com.xrtk.core/Services/BoundarySystem/MixedRealityBoundarySystem.cs
Labels: Bug, Ready for review

#523 Remove dead interface in diagnostics system
  XRTK-Core/Packages/com.xrtk.core/Interfaces/DiagnosticsSystem/IMixedRealityGenericDiagnosticsDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/DiagnosticsSystem/IMixedRealityGenericDiagnosticsDataProvider.cs.meta
Labels: Ready for review

#525 Fixed test warnings about monobehavours in editor folders
  XRTK-Core/Assets/XRTK.Tests/InputSystem/InputSystemTestUtilities.cs
  XRTK-Core/Assets/XRTK.Tests/Services/AssemblyInfo.cs
  XRTK-Core/Assets/XRTK.Tests/Services/AssemblyInfo.cs.meta
  XRTK-Core/Assets/XRTK.Tests/Services/InputSystem.meta
  XRTK-Core/Assets/XRTK.Tests/Services/InputSystem/TestGazeProvider.cs
  XRTK-Core/Assets/XRTK.Tests/Services/InputSystem/TestGazeProvider.cs.meta
  XRTK-Core/Assets/XRTK.Tests/Services/XRTK.Tests.Services.asmdef
  XRTK-Core/Assets/XRTK.Tests/Services/XRTK.Tests.Services.asmdef.meta
  XRTK-Core/Assets/XRTK.Tests/XRTK.Tests.asmdef
Labels: Bug, Ready for review

#526 Change requests for controller provider inspectors
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/Simulation/SimulatedControllerDataProviderProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/EditorGUILayoutExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Extensions/EditorGUILayoutExtensions.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/Controllers/BaseMixedRealityControllerDataProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/Controllers/Hands/BaseMixedRealityHandControllerDataProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/Controllers/Simulation/SimulatedControllerDataProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/InputSystem/Controllers/Simulation/SimulatedHandControllerDataProviderProfileInspector.cs
Labels: Ready for review

#530 Added platform overrides
  XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/BasePlatform.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/CurrentBuildTargetPlatform.cs
  XRTK-Core/Packages/com.xrtk.core/Interfaces/IMixedRealityPlatform.cs
  XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
Labels: Enhancement, Ready for review

#529 Added configuration foldout to all service configuration profiles
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityServiceProviderProfileInspector.cs
Labels: Enhancement, Ready for review

#534 Added IMixedRealityServiceProfile<out TService>
  XRTK-Core/Packages/com.xrtk.core/Definitions/BaseMixedRealityServiceProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
  XRTK-Core/Packages/com.xrtk.core/Utilities/ValidateConfiguration.cs
Labels: Breaking Change, Bug, Ready for review

#538 updated check for current build target
  XRTK-Core/Packages/com.xrtk.core/Definitions/Platforms/CurrentBuildTargetPlatform.cs
  XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
Labels: Bug, Ready for review

#543 Fix/input action regression
  XRTK-Core/Packages/com.xrtk.core/Definitions/InputSystem/MixedRealityInputAction.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/MixedRealityInputActionDropdown.cs
Labels: Bug, Ready for review

#546 Hotfix/0.1.33
  XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
  XRTK-Core/Packages/com.xrtk.core/package.json
Labels: Bug, Ready for review

#547 fixed duplicate global profile entry in the camera system profile inspector
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityCameraSystemProfileInspector.cs
Labels: Bug, Ready for review

#550 Azure Pipelines Yaml Upgrade
  README.md
  azure-pipelines.yml
  azure_pipelines/common.yml
  azure_pipelines/stages/publish.yml
  azure_pipelines/stages/steps/build-docfx.yml
  azure_pipelines/stages/steps/build-unity-player.yml
  azure_pipelines/stages/steps/export-package-seed.yml
  azure_pipelines/stages/steps/install-unity.yml
  azure_pipelines/stages/steps/return-unity-license.yml
  azure_pipelines/stages/steps/run-unity-tests.yml
  azure_pipelines/stages/steps/upm-package-info.yml
  azure_pipelines/stages/unity-build.yml
Labels: Enhancement, In Progress, Ready for review

#555 Fixed NRE in input system profile inspector
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/MixedRealityInputSystemProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/ArrayExtensions.cs
Labels: Bug, Ready for review
