Repository XRTK/com.xrtk.core, pull requests merged in 2020-03, with the labels that each got.

#462 Fix controller popup nre's for new controller
  XRTK-Core/Packages/com.xrtk.core/Inspectors/ControllerPopupWindow.cs
Labels: Ready for review

#464 Added a remark to the ArrayExtensions ArrayInitialise function
  XRTK-Core/Packages/com.xrtk.core/Extensions/ArrayExtensions.cs
Labels: Ready for review

#465 Removed some resharper errors in the tests
  XRTK-Core/Assets/XRTK.Tests/Core/TestFixture_03_ExtensionsTests.cs
Labels: Ready for review

#470 Fixes to correctly filter for nested services/data providers in the new configuraitons inspector
  XRTK-Core/Assets/XRTK.Tests/Services/ITestDataProvider1.cs
  XRTK-Core/Assets/XRTK.Tests/Services/ITestExtensionServiceProvider1.cs
  XRTK-Core/Assets/XRTK.Tests/Services/TestExtensionService1.cs
  XRTK-Core/Assets/XRTK.Tests/Services/TestExtensionServiceProvider1.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/BaseMixedRealityExtensionServiceProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Definitions/BaseMixedRealityExtensionServiceProfile.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Extensions/TypeExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Extensions/TypeExtensions.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityServiceProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Services/BaseExtensionService.cs
Labels: Bug, Ready for review

#472 Fix/471 extension service providers
  XRTK-Core/Packages/com.xrtk.core/Services/MixedRealityToolkit.cs
Labels: Bug, In Progress

#478 Fixed some issues with the MixedRealityServiceProfileInspector
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/BaseMixedRealityProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/Profiles/MixedRealityServiceProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Inspectors/PropertyDrawers/TypeReferencePropertyDrawer.cs
Labels: Bug, Ready for review

#480 updated simulated hand data profile with required fields for IMixedRealityHandControllerDataProvider
  XRTK-Core/Packages/com.xrtk.core/Definitions/Controllers/Simulation/Hands/SimulatedHandControllerDataProviderProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Providers/Controllers/Simulation/Hands/SimulatedHandControllerDataProvider.cs
Labels: Ready for review

#479 Updated project settings
  .gitignore
  XRTK-Core/ProjectSettings/ProjectSettings.asset
Labels: Ready for review
