Repository XRTK/com.xrtk.core, pull requests merged in 2020-05, with the labels that each got.

#562 Added guid regeneration for installed package profiles to prevent asset collisions
  XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs.meta
Labels: Enhancement, Ready for review

#565 Disabled package installation button in xrtk.core project
  XRTK-Core/Assets/XRTK.Seed/PackagePickerWindow.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Editor/MixedRealityEditorSettings.cs
Labels: Enhancement, Ready for review

#566 Fixed a bug where profile field assignment was not working
  XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/MixedRealityProfilePropertyDrawer.cs
Labels: Bug, Ready for review

#568 fixed naming of BaseMixedRealityProfileExtensions name
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/BaseMixedRealityProfileInspectorExtensions.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/BaseMixedRealityProfileInspectorExtensions.cs.meta
Labels: Ready for review

#570 Feature/service wizard
  XRTK-Core/Assets/XRTK.Seed/PackagePickerWindow.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/BaseMixedRealityProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityServiceProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/TypeReferencePropertyDrawer.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Templates~/DataProvider.txt
  XRTK-Core/Packages/com.xrtk.core/Editor/Templates~/DataProviderProfile.txt
  XRTK-Core/Packages/com.xrtk.core/Editor/Templates~/Service.txt
  XRTK-Core/Packages/com.xrtk.core/Editor/Templates~/ServiceProfile.txt
  XRTK-Core/Packages/com.xrtk.core/Editor/Templates~/System.txt
  XRTK-Core/Packages/com.xrtk.core/Editor/Templates~/SystemProfile.txt
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/MixedRealityInspectorUtility.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/MixedRealityServiceWizard.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/MixedRealityServiceWizard.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/BaseMixedRealityServiceProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystemProfile.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/EventDatum/SpatialAwareness/MixedRealitySpatialAwarenessEventData.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/CameraSystem/IMixedRealityCameraSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/DiagnosticsSystem/IMixedRealityDiagnosticsSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/EventSystem/IMixedRealityEventSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/IMixedRealitySystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/IMixedRealitySystem.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/Providers/SpatialObservers/IMixedRealitySpatialAwarenessDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/Providers/SpatialObservers/IMixedRealitySpatialAwarenessDataProvider.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/Providers/SpatialObservers/IMixedRealitySpatialMeshObserver.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/Providers/SpatialObservers/IMixedRealitySpatialSurfaceObserver.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/SpatialAwareness/IMixedRealitySpatialAwarenessSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/SpatialObservers/BaseMixedRealitySpatialObserverDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/BaseExtensionDataProvider.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/BaseExtensionService.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/BaseServiceWithConstructor.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/BaseSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/SpatialAwarenessSystem/MixedRealitySpatialAwarenessSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/TeleportSystem/MixedRealityTeleportSystem.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/Editor/PathFinderUtility.cs
Labels: Breaking Change, Enhancement, Ready for review

#574 Dev/update unity installer
  azure-pipelines.yml
  azure_pipelines/stages/steps/install-unity.yml
Labels: Enhancement

#572 Don't add the registry if it already exists
  XRTK-Core/Assets/XRTK.Seed/MixedRealityPackageSeed.cs
Labels: Bug, Ready for review

#575 Fixed rendering problems for 2019
  XRTK-Core/Packages/com.xrtk.core/Editor/BaseMixedRealityToolkitInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/BaseMixedRealityToolkitInspector.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Editor/ControllerPopupWindow.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityToolkitInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/BaseMixedRealityProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/InputSystem/Controllers/BaseMixedRealityControllerDataProviderProfileInspector.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/MixedRealityProfilePropertyDrawer.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/MixedRealityInspectorUtility.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/BaseController.cs
Labels: Bug, Ready for review

#578 Update OpenVR for Oculus Quest controller name change
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/OpenVR/OpenVRControllerDataProvider.cs
Labels: Bug, Ready for review

#580 added upm preview package publishing capabilities
  azure-pipelines.yml
  azure_pipelines/common.yml
  azure_pipelines/stages/publish.yml
  azure_pipelines/stages/steps/build-docfx.yml
  azure_pipelines/stages/steps/build-docs.yml
  azure_pipelines/stages/steps/export-package-seed.yml
  azure_pipelines/stages/steps/run-unity-tests.yml
  azure_pipelines/stages/steps/upm-package-info.yml
  azure_pipelines/stages/unity-build.yml
Labels: Enhancement, Feature Request, Ready for review

#582 updated github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/request_for_information.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Enhancement, Ready for review

#581 only regen guids on new installation
  XRTK-Core/Packages/com.xrtk.core/Editor/PackageInstaller.cs
Labels: Bug, Ready for review

#586 fixed standard editor shader reference
  XRTK-Core/Packages/com.xrtk.core/Runtime/StandardAssets/Shaders/MixedRealityStandard.shader
Labels: Bug, Ready for review

#587 Updated handedness to properly work with the enum flags attribute
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Utilities/Handedness.cs
Labels: Bug, Ready for review

#588 Dev/updated project settings
  .gitignore
  XRTK-Core/Packages/com.xrtk.core/Runtime/StandardAssets/Textures/xrtk_logo_transparent_square.png
  XRTK-Core/Packages/com.xrtk.core/Runtime/StandardAssets/Textures/xrtk_logo_transparent_square.png.meta
  XRTK-Core/Packages/manifest.json
  XRTK-Core/ProjectSettings/ProjectSettings.asset
Labels: Enhancement, Ready for review

#589 dev/updated controller info
  XRTK-Core/Packages/com.xrtk.core/Runtime/Interfaces/Providers/Controllers/IMixedRealityController.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/BaseController.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/BaseControllerDataProvider.cs
Labels: Enhancement, Ready for review

#593 Fix endless configure toolkit dialog issue
  XRTK-Core/Packages/com.xrtk.core/Editor/Profiles/MixedRealityToolkitRootProfileInspector.cs
Labels: Bug, Ready for review

#597 Fixed package seed so it doesn't add registry more than once
  XRTK-Core/Assets/XRTK.Seed/MixedRealityPackageSeed.cs
Labels: Bug, Ready for review

#600 Fixed Editor Only services
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Platforms/CurrentBuildTargetPlatform.cs
Labels: Bug

#601 fixed some errors with meta files in 2019
  XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/AxisConstraintAttributeDrawer.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Editor/PropertyDrawers/MixedRealityInputActionDropdown.cs.meta
Labels: Bug, Ready for review

#609 updated mouse input
  XRTK-Core/Assets/XRTK.Generated/_TestProfiles/TestMixedRealityToolkitRootProfile/MixedRealityInputSystemProfile.asset
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/UnityInput/MouseController.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/UnityInput/MouseDataProvider.cs
Labels: Bug, Ready for review

#617 Misc changes to pose processor and hand controller
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Hands/HandTrackedPoseProcessor.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/Controllers/Hands/MixedRealityHandController.cs
Labels: Ready for review

#620 Fixed UnauthorizedAccessException when installing packages
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/GuidRegenerator.cs
Labels: Bug, Ready for review
