Repository XRTK/com.xrtk.core, pull requests merged in 2020-06, with the labels that each got.

#625 Fixed some service generation issues with with service wizard
  XRTK-Core/Packages/com.xrtk.core/Editor/Templates~/DataProvider.txt
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/MixedRealityServiceWizard.cs
Labels: Bug, Enhancement, Ready for review

#627 Fixed some warnings and errors when starting/stopping playmode in editor
  XRTK-Core/Packages/com.xrtk.core/Runtime/Providers/SpatialObservers/BaseMixedRealitySpatialMeshObserver.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
Labels: Bug, Enhancement, Ready for review

#631 Don't add command arg if we're not actually processing a terminal command
  XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/ProcessExtensions.cs
Labels: Bug, Ready for review

#632 optimized perf when looking up types by guid
  XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/TypeExtensions.cs
Labels: Enhancement, Ready for review

#638 Fix android CI/CD builds
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/BuildAndDeploy/UnityPlayerBuildTools.cs
  azure_pipelines/common.yml
  azure_pipelines/stages/steps/install-unity.yml
  azure_pipelines/stages/unity-build.yml
Labels: Ready for review

#637 Pull out Quaternion.Approximately from hands PR
  XRTK-Core/Packages/com.xrtk.core/Runtime/Extensions/QuaternionExtensions.cs
Labels: Ready for review

#636 Revert API level to 25 for Quest build support
  XRTK-Core/ProjectSettings/ProjectSettings.asset
Labels: Ready for review

#640 CI/CD Fixes
  azure_pipelines/stages/steps/build-unity-player.yml
  azure_pipelines/stages/steps/export-package-seed.yml
  azure_pipelines/stages/steps/install-unity.yml
  azure_pipelines/stages/steps/return-unity-license.yml
  azure_pipelines/stages/steps/run-unity-tests.yml
  azure_pipelines/stages/unity-build.yml
Labels: Ready for review

#642 fixed android build warnings about the logo
  XRTK-Core/Packages/com.xrtk.core/Runtime/StandardAssets/Textures/xrtk_logo_transparent_square.png.meta
Labels: Ready for review

#644 Update ControllerPopupWindow.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/ControllerPopupWindow.cs
Labels: Ready for review

#646 Fix profiles reset and services reinitialized when already running
  XRTK-Core/Packages/com.xrtk.core/Runtime/Services/MixedRealityToolkit.cs
Labels: Bug, Ready for review
