Repository XRTK/com.xrtk.core, pull requests merged in 2021-01, with the labels that each got.

#754 Fix auto scene switcher dialog appearing when toolkit is already active and configured
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/AutoSceneSwitcher.cs
Labels: Ready for review

#755 Bump Core version
  XRTK-Core/Packages/com.xrtk.core/package.json
Labels: Ready for review

#757 Fix NRE in EditorActiveProfileChangeHandler
  XRTK-Core/Packages/com.xrtk.core/Editor/EditorActiveProfileChangeHandler.cs
Labels: Ready for review

#761 updated assertion check when configuring the start scene
  XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityToolkitInspector.cs
Labels: Bug, Ready for review

#760 Fixed auto-configuration without user input
  XRTK-Core/Packages/com.xrtk.core/Editor/EditorActiveProfileChangeHandler.cs
Labels: Bug, Ready for review

#766 Implement utility to check for used render pipeline
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Utilities/RenderPipeline.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Definitions/Utilities/RenderPipeline.cs.meta
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/RenderPipelineUtilities.cs
  XRTK-Core/Packages/com.xrtk.core/Runtime/Utilities/RenderPipelineUtilities.cs.meta
Labels: Ready for review

#770 Added a ValidateProject method to build tools
  XRTK-Core/Packages/com.xrtk.core/Editor/BuildAndDeploy/UnityPlayerBuildTools.cs
Labels: Breaking Change, Ready for review

#772 Fixed XRTK auto-initialization for auto scene switcher
  XRTK-Core/Packages/com.xrtk.core/Editor/MixedRealityPreferences.cs
  XRTK-Core/Packages/com.xrtk.core/Editor/Utilities/AutoSceneSwitcher.cs
  XRTK-Core/Packages/manifest.json
  XRTK-Core/Packages/packages-lock.json
Labels: Ready for review
